# Generated by Django 2.1.5 on 2019-03-29 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_ext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ext', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'File_ext',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Url',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Url_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_path', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('file_ext_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dirscan.File_ext')),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dirscan.Url')),
            ],
            options={
                'db_table': 'Url_status',
                'ordering': ['id'],
            },
        ),
    ]
