# Generated by Django 2.1.5 on 2019-06-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirscan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dir_domain',
            name='domain',
            field=models.CharField(max_length=100),
        ),
    ]
