# Generated by Django 2.1.5 on 2019-06-04 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20, null=True)),
                ('product', models.CharField(max_length=20, null=True)),
                ('version', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'Port_detail',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Port_domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=20)),
                ('createtime', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'port_domain',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='port_detail',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portscan.Port_domain'),
        ),
    ]
